### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by mnekx** [mwafrika/space_traveller_hub#25]
In this milestone, we assigned tasks for every member fairly according to the [Kanban project here](https://github.com/mwafrika/space_traveller_hub/projects/1).

 * We are a group of three.

**Comment by Meltrust** [comment]
Hi team,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)



### To highlight:

- The board meets the requirements!✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
